version: '3'
services:
    keyrock:
        image: fiware/idm
        container_name: fiware-keyrock
        expose: 
            - 3005
        ports:
            - '3005:3005'
            - '3443:3443'
        environment:
            - IDM_DB_HOST=mysql-db
            - IDM_HOST=http://localhost:3005
            - IDM_PORT=3005
        links:
            - mysql-db
        volumes:
            - .:/fiware/keyrockIDM

    mysql-db:
        container_name: sql
        image: mysql/mysql-server:5.7.21
        expose:
            - '3306'
        ports:
            - '3306:3306'
        environment:
            - 'MYSQL_ROOT_PASSWORD=idm'
            - 'MYSQL_ROOT_HOST=%'
        volumes:
            - ./dbDATAS/keyrock_db:/var/lib/mysql
    www:
        build: .
        image: php:7.4-apache
        ports: 
            - "3001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mongodb-data
        
    mongodb-data:
        image: mongo
        restart: always
        ports:
        - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:
            - ./dbDATAS/mongo-server:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
             - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_SERVER: mongodb-data

    mongo:
        image: mongo:3.6
        command: --nojournal
        volumes:
            - ./dbDATAS/mongo:/data/db

    pepwilma:
        image: fiware/pep-proxy
        hostname: pepwilma
        links:
            - www
            - keyrock
        ports: 
            - 1027:1027
        environment:
            - PEP_PROXY_APP_HOST=www
            - PEP_PROXY_APP_PORT=80
            - PEP_PROXY_APP_ID=f3e438e3-55df-4a8b-90d3-3fd520b74740
            - PEP_PROXY_USERNAME=pep_proxy_95dad6c5-a274-4acb-aa58-a643921e2cf2
            - PEP_PASSWORD=pep_proxy_fe209a61-b6f2-47ff-ab00-efa2e547f26d
            - PEP_PROXY_IDM_HOST=keyrock
            - PEP_PROXY_IDM_PORT=3005
            - PEP_PROXY_PORT= 1027
        healthcheck:
          test: curl --fail -s http://pepwilma:1027/version || exit 1